apiVersion: apps/v1
kind: Deployment
metadata:
  name: xm-fernc-python
  namespace: xm-fernc-python-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xm-fernc-python
  template:
    metadata:
      labels:
        app: xm-fernc-python
    spec:
      containers:
      - name: #{ECR_REPOSITORY_NAME}#
        image: acrxmtransversal.azurecr.io/#{ECR_REPOSITORY_NAME}#:#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
        - name: ENVIRONMENT
          value: #{APP_ENVIRONMENT}#
        - name: AZURE_TENANT_ID
          value: #{APP_AZURE_TENANT_ID}#
        - name: AZURE_CLIENT_ID
          value: #{APP_AZURE_CLIENT_ID}#
        - name: AZURE_CLIENT_SECRET
          value: #{APP_AZURE_CLIENT_SECRET}#
        - name: AZURE_SUBSCRIPTION_ID
          value: #{APP_AZURE_SUBSCRIPTION_ID}#
        - name: KEYVAULT_URI
          value: #{APP_KEYVAULT_URI}#
        - name: KEYVAULT_STORAGE_ACOUNT
          value: #{APP_KEYVAULT_STORAGE_ACOUNT}#
        - name: CONTAINER
          value: #{APP_CONTAINER}#
        resources:
          requests:
            memory: "5000Mi"
            cpu: "1200m"
          limits:
            memory: "7500Mi"
            cpu: "2000m"
        
